dist: trusty
language: node_js
addons:
  mariadb: '10.0'
node_js:
  - "node"
before_script:
  - npm install
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
  - npm run postinstall
script:
  - npm run test
